Missing import in index.d.ts
There is a missing import (Address) in index.d.ts. I have the following error when trying to run my app :

ERROR in node_modules/nativescript-dna-deviceinfo/index.d.ts:31:29 - error TS2304: Cannot find name 'Address'.